#!/usr/bin/env bash
set -Eeuo pipefail

: "${WOKCORE_REAL_DPKG_DEB:?}"
if [[ "${1:-}" == "--build" &&
    "${WOKCORE_DPKG_DEB_EXTRA_NODE:-}" == symlink ]]; then
    arguments=("$@")
    package_root="${arguments[$(($# - 2))]}"
    ln -s /usr/bin/wokcore \
        "$package_root/usr/share/doc/wokcore/UNEXPECTED-LINK"
fi
"$WOKCORE_REAL_DPKG_DEB" "$@"
if [[ "${1:-}" == "--build" &&
    -z "${WOKCORE_DPKG_DEB_EXTRA_NODE:-}" ]]; then
    printf 'corrupt Debian package fixture\n' >"${!#}"
fi
